### ISSUE TITLE
[Feature Request]: Refactor db setup

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/Swate#332]
### Is your feature request related to a problem?

I will use this as a collection point for all database related issues.

- [x] https://github.com/nfdi4plants/Swate/issues/319, search returns unintuitive results
- [x] https://github.com/nfdi4plants/Swate/issues/315. search is not performant
- [x] https://github.com/nfdi4plants/Swate/issues/320, maybe use TIS?
- [x] https://github.com/nfdi4plants/Swate/issues/236, do not show or use queries ignoring obsolete terms
- [x] https://github.com/nfdi4plants/Swate/issues/306, correctly display OntologySourceReference as part of ontology object in db.

### Describe the solution you would like!

Either use TIS or setup 2 databases:

- neo4j for tree search
- any high performance string search database

1. search string only, 
2. use results to do tree search, but already return string search results.
3. Add to results from tree search results.

- remove user toggle for tree search and make it happen "magically" 

### Host

Standalone

### Host Details

All

**Comment by Freymaurer** [comment]
Will close all related issues as they are now collected here
